#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #3.JPA
  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000
ai:
  appId: 18818255
  apiKey: 5qOa4Hm2kM7Ycnie5oCLUGUG
  secretKey: h1a93OGQ9XXG8Ujkuyf97BE5G5FYWtQw
  imageType: BASE64
  groupId: itcast
qr:
  url: http://localhost:8080/#/facelogin
